// file was generated by kissmath.py at <TODO: add github link>
#include "uint.hpp"

namespace kissmath {
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	uint wrap (uint x, uint range) {
		uint modded = x % range;
		if (range > 0) {
			if (modded < 0) modded += range;
		} else {
			if (modded > 0) modded += range;
		}
		return modded;
	}
	
	// wrap x into [a,b) range
	uint wrap (uint x, uint a, uint b) {
		x -= a;
		uint range = b -a;
		
		uint modulo = wrap(x, range);
		
		return modulo + a;
	}
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	uint clamp (uint x, uint a, uint b) {
		return min(max(x, a), b);
	}
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	uint clamp (uint x) {
		return min(max(x, uint(0)), uint(1));
	}
	
	// returns the greater value of a and b
	uint min (uint l, uint r) {
		return l <= r ? l : r;
	}
	
	// returns the smaller value of a and b
	uint max (uint l, uint r) {
		return l >= r ? l : r;
	}
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	uint select (bool c, uint l, uint r) {
		return c ? l : r;
	}
	
}

