// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include <cmath>
#include <cstdint>

namespace kissmath {
	typedef unsigned int uint; // typedef this because the _t suffix is kinda unwieldy when using these types often
	
	// Use std math functions for these
	using std::abs;
	using std::floor;
	using std::ceil;
	using std::pow;
	using std::round;
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	uint wrap (uint x, uint range);
	
	// wrap x into [a,b) range
	uint wrap (uint x, uint a, uint b);
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	uint clamp (uint x, uint a, uint b);
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	uint clamp (uint x);
	
	// returns the greater value of a and b
	uint min (uint l, uint r);
	
	// returns the smaller value of a and b
	uint max (uint l, uint r);
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	uint select (bool c, uint l, uint r);
	
	
}

