// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "double2.hpp"
#include "double3.hpp"

namespace kissmath {
	
	//// matrix forward declarations
	struct double2x2;
	struct double3x3;
	struct double4x4;
	struct double3x4;
	struct float2x3;
	
	struct double2x3 {
		double2 arr[3]; // column major for compatibility with OpenGL
		
		//// Accessors
		
		// get cell with row, column indecies
		double const& get (int r, int c) const;
		
		// get matrix column
		double2 const& get_column (int indx) const;
		
		// get matrix row
		double3 get_row (int indx) const;
		
		
		//// Constructors
		
		// uninitialized constructor
		double2x3 ();
		
		// supply one value for all cells
		explicit double2x3 (double all);
		
		// supply all cells, in row major order for readability -> c<row><column>
		explicit double2x3 (double c00, double c01, double c02,
							double c10, double c11, double c12);
		
		
		// static rows() and columns() methods are preferred over constructors, to avoid confusion if column or row vectors are supplied to the constructor
		// supply all row vectors
		static double2x3 rows (double3 row0, double3 row1);
		
		// supply all cells in row major order
		static double2x3 rows (double c00, double c01, double c02,
							   double c10, double c11, double c12);
		
		// supply all column vectors
		static double2x3 columns (double2 col0, double2 col1, double2 col2);
		
		// supply all cells in column major order
		static double2x3 columns (double c00, double c10,
								  double c01, double c11,
								  double c02, double c12);
		
		
		// identity matrix
		static double2x3 identity ();
		
		
		// Casting operators
		
		// extend/truncate matrix of other size
		explicit operator double2x2 () const;
		
		// extend/truncate matrix of other size
		explicit operator double3x3 () const;
		
		// extend/truncate matrix of other size
		explicit operator double4x4 () const;
		
		// extend/truncate matrix of other size
		explicit operator double3x4 () const;
		
		// typecast
		explicit operator float2x3 () const;
		
		
		// Componentwise operators; These might be useful in some cases
		
		// add scalar to all matrix cells
		double2x3& operator+= (double r);
		
		// substract scalar from all matrix cells
		double2x3& operator-= (double r);
		
		// multiply scalar with all matrix cells
		double2x3& operator*= (double r);
		
		// divide all matrix cells by scalar
		double2x3& operator/= (double r);
		
		
		// Matrix multiplication
		
		// matrix-matrix muliplication
		double2x3& operator*= (double2x3 const& r);
		
	};
	
	// Componentwise operators; These might be useful in some cases
	
	
	// componentwise matrix_cell + matrix_cell
	double2x3 operator+ (double2x3 const& l, double2x3 const& r);
	
	// componentwise matrix_cell + scalar
	double2x3 operator+ (double2x3 const& l, double r);
	
	// componentwise scalar + matrix_cell
	double2x3 operator+ (double l, double2x3 const& r);
	
	
	// componentwise matrix_cell - matrix_cell
	double2x3 operator- (double2x3 const& l, double2x3 const& r);
	
	// componentwise matrix_cell - scalar
	double2x3 operator- (double2x3 const& l, double r);
	
	// componentwise scalar - matrix_cell
	double2x3 operator- (double l, double2x3 const& r);
	
	
	// componentwise matrix_cell * matrix_cell
	double2x3 mul_componentwise (double2x3 const& l, double2x3 const& r);
	
	// componentwise matrix_cell * scalar
	double2x3 operator* (double2x3 const& l, double r);
	
	// componentwise scalar * matrix_cell
	double2x3 operator* (double l, double2x3 const& r);
	
	
	// componentwise matrix_cell / matrix_cell
	double2x3 div_componentwise (double2x3 const& l, double2x3 const& r);
	
	// componentwise matrix_cell / scalar
	double2x3 operator/ (double2x3 const& l, double r);
	
	// componentwise scalar / matrix_cell
	double2x3 operator/ (double l, double2x3 const& r);
	
	
	// Matrix ops
	
	// matrix-matrix multiply
	double2x3 operator* (double2x3 const& l, double3x3 const& r);
	
	// double2x3 * double3x4 -> 2x4 ; matrix not implemented
	// matrix-vector multiply
	double2 operator* (double2x3 const& l, double3 r);
	
	// vector-matrix multiply
	double3 operator* (double2 l, double2x3 const& r);
	
	
	// Matrix operation shortforms so that you can treat a 2x3 matrix as a 2x2 matrix plus translation
	
	// shortform for double2x3 * (double3x3)double2x2
	double2x3 operator* (double2x3 const& l, double2x2 const& r);
	
	// shortform for double2x3 * (double3x3)double2x3
	double2x3 operator* (double2x3 const& l, double2x3 const& r);
	
	// shortform for double2x3 * double3(double2, 1)
	double2 operator* (double2x3 const& l, double2 r);
	
}

