// file was generated by kissmath.py at <TODO: add github link>
#include "double3.hpp"

#include "int3.hpp"
#include "uint64v3.hpp"
#include "uint16v3.hpp"
#include "bool3.hpp"
#include "int8v3.hpp"
#include "int16v3.hpp"
#include "double4.hpp"
#include "uint8v3.hpp"
#include "double2.hpp"
#include "uint3.hpp"
#include "float3.hpp"
#include "int64v3.hpp"

namespace kissmath {
	//// forward declarations
	// typedef these because the _t suffix is kinda unwieldy when using these types often
	
	typedef uint64_t uint64;
	typedef uint16_t uint16;
	typedef int8_t int8;
	typedef int16_t int16;
	typedef uint8_t uint8;
	typedef unsigned int uint;
	typedef int64_t int64;
	
	// Component indexing operator
	double& double3::operator[] (int i) {
		return arr[i];
	}
	
	// Component indexing operator
	double const& double3::operator[] (int i) const {
		return arr[i];
	}
	
	
	// uninitialized constructor
	double3::double3 () {
		
	}
	
	// sets all components to one value
	// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
	// and short initialization like float3 a = 0; works
	double3::double3 (double all): x{all}, y{all}, z{all} {
		
	}
	
	// supply all components
	double3::double3 (double x, double y, double z): x{x}, y{y}, z{z} {
		
	}
	
	// extend vector
	double3::double3 (double2 xy, double z): x{xy.x}, y{xy.y}, z{z} {
		
	}
	
	// truncate vector
	double3::double3 (double4 v): x{v.x}, y{v.y}, z{v.z} {
		
	}
	
	//// Truncating cast operators
	
	
	// truncating cast operator
	double3::operator double2 () const {
		return double2(x, y);
	}
	
	//// Type cast operators
	
	
	// type cast operator
	double3::operator bool3 () const {
		return bool3((bool)x, (bool)y, (bool)z);
	}
	
	// type cast operator
	double3::operator float3 () const {
		return float3((float)x, (float)y, (float)z);
	}
	
	// type cast operator
	double3::operator int8v3 () const {
		return int8v3((int8)x, (int8)y, (int8)z);
	}
	
	// type cast operator
	double3::operator int16v3 () const {
		return int16v3((int16)x, (int16)y, (int16)z);
	}
	
	// type cast operator
	double3::operator int3 () const {
		return int3((int)x, (int)y, (int)z);
	}
	
	// type cast operator
	double3::operator int64v3 () const {
		return int64v3((int64)x, (int64)y, (int64)z);
	}
	
	// type cast operator
	double3::operator uint8v3 () const {
		return uint8v3((uint8)x, (uint8)y, (uint8)z);
	}
	
	// type cast operator
	double3::operator uint16v3 () const {
		return uint16v3((uint16)x, (uint16)y, (uint16)z);
	}
	
	// type cast operator
	double3::operator uint3 () const {
		return uint3((uint)x, (uint)y, (uint)z);
	}
	
	// type cast operator
	double3::operator uint64v3 () const {
		return uint64v3((uint64)x, (uint64)y, (uint64)z);
	}
	
	
	// componentwise arithmetic operator
	double3 double3::operator+= (double3 r) {
		x += r.x;
		y += r.y;
		z += r.z;
		return *this;
	}
	
	// componentwise arithmetic operator
	double3 double3::operator-= (double3 r) {
		x -= r.x;
		y -= r.y;
		z -= r.z;
		return *this;
	}
	
	// componentwise arithmetic operator
	double3 double3::operator*= (double3 r) {
		x *= r.x;
		y *= r.y;
		z *= r.z;
		return *this;
	}
	
	// componentwise arithmetic operator
	double3 double3::operator/= (double3 r) {
		x /= r.x;
		y /= r.y;
		z /= r.z;
		return *this;
	}
	
	//// arthmethic ops
	
	
	double3 operator+ (double3 v) {
		return double3(+v.x, +v.y, +v.z);
	}
	
	double3 operator- (double3 v) {
		return double3(-v.x, -v.y, -v.z);
	}
	
	double3 operator+ (double3 l, double3 r) {
		return double3(l.x + r.x, l.y + r.y, l.z + r.z);
	}
	
	double3 operator- (double3 l, double3 r) {
		return double3(l.x - r.x, l.y - r.y, l.z - r.z);
	}
	
	double3 operator* (double3 l, double3 r) {
		return double3(l.x * r.x, l.y * r.y, l.z * r.z);
	}
	
	double3 operator/ (double3 l, double3 r) {
		return double3(l.x / r.x, l.y / r.y, l.z / r.z);
	}
	
	//// bitwise ops
	
	
	//// comparison ops
	
	
	// componentwise comparison returns a bool vector
	bool3 operator< (double3 l, double3 r) {
		return bool3(l.x < r.x, l.y < r.y, l.z < r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator<= (double3 l, double3 r) {
		return bool3(l.x <= r.x, l.y <= r.y, l.z <= r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator> (double3 l, double3 r) {
		return bool3(l.x > r.x, l.y > r.y, l.z > r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator>= (double3 l, double3 r) {
		return bool3(l.x >= r.x, l.y >= r.y, l.z >= r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator== (double3 l, double3 r) {
		return bool3(l.x == r.x, l.y == r.y, l.z == r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator!= (double3 l, double3 r) {
		return bool3(l.x != r.x, l.y != r.y, l.z != r.z);
	}
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (double3 l, double3 r) {
		return all(l == r);
	}
	
	// componentwise ternary (c ? l : r)
	double3 select (bool3 c, double3 l, double3 r) {
		return double3(c.x ? l.x : r.x, c.y ? l.y : r.y, c.z ? l.z : r.z);
	}
	
	//// misc ops
	
	// componentwise absolute
	double3 abs (double3 v) {
		return double3(abs(v.x), abs(v.y), abs(v.z));
	}
	
	// componentwise minimum
	double3 min (double3 l, double3 r) {
		return double3(min(l.x,r.x), min(l.y,r.y), min(l.z,r.z));
	}
	
	// componentwise maximum
	double3 max (double3 l, double3 r) {
		return double3(max(l.x,r.x), max(l.y,r.y), max(l.z,r.z));
	}
	
	// componentwise clamp into range [a,b]
	double3 clamp (double3 x, double3 a, double3 b) {
		return min(max(x,a), b);
	}
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	double3 clamp (double3 x) {
		return min(max(x, double(0)), double(1));
	}
	
	// get minimum component of vector, optionally get component index via min_index
	double min_component (double3 v, int* min_index) {
		int index = 0;
		double min_val = v.x;	
		for (int i=1; i<3; ++i) {
			if (v.arr[i] <= min_val) {
				index = i;
				min_val = v.arr[i];
			}
		}
		if (min_index) *min_index = index;
		return min_val;
	}
	
	// get maximum component of vector, optionally get component index via max_index
	double max_component (double3 v, int* max_index) {
		int index = 0;
		double max_val = v.x;	
		for (int i=1; i<3; ++i) {
			if (v.arr[i] >= max_val) {
				index = i;
				max_val = v.arr[i];
			}
		}
		if (max_index) *max_index = index;
		return max_val;
	}
	
	
	// componentwise floor
	double3 floor (double3 v) {
		return double3(floor(v.x), floor(v.y), floor(v.z));
	}
	
	// componentwise ceil
	double3 ceil (double3 v) {
		return double3(ceil(v.x), ceil(v.y), ceil(v.z));
	}
	
	// componentwise round
	double3 round (double3 v) {
		return double3(round(v.x), round(v.y), round(v.z));
	}
	
	// componentwise floor to int
	int64v3 floori (double3 v) {
		return int64v3(floori(v.x), floori(v.y), floori(v.z));
	}
	
	// componentwise ceil to int
	int64v3 ceili (double3 v) {
		return int64v3(ceili(v.x), ceili(v.y), ceili(v.z));
	}
	
	// componentwise round to int
	int64v3 roundi (double3 v) {
		return int64v3(roundi(v.x), roundi(v.y), roundi(v.z));
	}
	
	// componentwise pow
	double3 pow (double3 v, double3 e) {
		return double3(pow(v.x,e.x), pow(v.y,e.y), pow(v.z,e.z));
	}
	
	// componentwise wrap
	double3 wrap (double3 v, double3 range) {
		return double3(wrap(v.x,range.x), wrap(v.y,range.y), wrap(v.z,range.z));
	}
	
	// componentwise wrap
	double3 wrap (double3 v, double3 a, double3 b) {
		return double3(wrap(v.x,a.x,b.x), wrap(v.y,a.y,b.y), wrap(v.z,a.z,b.z));
	}
	
	
	//// Angle conversion
	
	
	// converts degrees to radiants
	double3 to_radians (double3 deg) {
		return deg * DEG_TO_RADd;
	}
	
	// converts radiants to degrees
	double3 to_degrees (double3 rad) {
		return rad * RAD_TO_DEGd;
	}
	
	// converts degrees to radiants
	// shortform to make degree literals more readable
	double3 deg (double3 deg) {
		return deg * DEG_TO_RADd;
	}
	
	// linear interpolation
	// like getting the output of a linear function
	// ex. t=0 -> a ; t=1 -> b ; t=0.5 -> (a+b)/2
	double3 lerp (double3 a, double3 b, double3 t) {
		return t * (b - a) + a;
	}
	
	// linear mapping
	// sometimes called inverse linear interpolation
	// like getting the x for a y on a linear function
	// ex. map(70, 0,100) -> 0.7 ; map(0.5, -1,+1) -> 0.75
	double3 map (double3 x, double3 in_a, double3 in_b) {
		return (x - in_a) / (in_b - in_a);
	}
	
	// linear remapping
	// equivalent of lerp(out_a, out_b, map(x, in_a, in_b))
	double3 map (double3 x, double3 in_a, double3 in_b, double3 out_a, double3 out_b) {
		return lerp(out_a, out_b, map(x, in_a, in_b));
	}
	
	//// Various interpolation
	
	
	// standard smoothstep interpolation
	double3 smoothstep (double3 x) {
		double3 t = clamp(x);
		return t * t * (3.0 - 2.0 * t);
	}
	
	// 3 point bezier interpolation
	double3 bezier (double3 a, double3 b, double3 c, double t) {
		double3 d = lerp(a, b, t);
		double3 e = lerp(b, c, t);
		double3 f = lerp(d, e, t);
		return f;
	}
	
	// 4 point bezier interpolation
	double3 bezier (double3 a, double3 b, double3 c, double3 d, double t) {
		return bezier(
					  lerp(a, b, t),
					  lerp(b, c, t),
					  lerp(c, d, t),
					  t
			   );
	}
	
	// 5 point bezier interpolation
	double3 bezier (double3 a, double3 b, double3 c, double3 d, double3 e, double t) {
		return bezier(
					  lerp(a, b, t),
					  lerp(b, c, t),
					  lerp(c, d, t),
					  lerp(d, e, t),
					  t
			   );
	}
	
	//// Vector math
	
	
	// magnitude of vector
	double length (double3 v) {
		return sqrt((double)(v.x * v.x + v.y * v.y + v.z * v.z));
	}
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	double length_sqr (double3 v) {
		return v.x * v.x + v.y * v.y + v.z * v.z;
	}
	
	// distance between points, equivalent to length(a - b)
	double distance (double3 a, double3 b) {
		return length(a - b);
	}
	
	// normalize vector so that it has length() = 1, undefined for zero vector
	double3 normalize (double3 v) {
		return double3(v) / length(v);
	}
	
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	double3 normalizesafe (double3 v) {
		double len = length(v);
		if (len == double(0)) {
			return double(0);
		}
		return double3(v) / double3(len);
	}
	
	// dot product
	double dot (double3 l, double3 r) {
		return l.x * r.x + l.y * r.y + l.z * r.z;
	}
	
	// 3d cross product
	double3 cross (double3 l, double3 r) {
		return double3(
					   l.y * r.z - l.z * r.y,
					   l.z * r.x - l.x * r.z,
					   l.x * r.y - l.y * r.x);
	}
}

