// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "int16.hpp"

namespace kissmath {
	//// forward declarations
	
	struct uint8v4;
	struct uint4;
	struct int64v4;
	struct int8v4;
	struct float4;
	struct bool4;
	struct uint16v4;
	struct int16v2;
	struct uint64v4;
	struct int16v3;
	struct double4;
	struct int4;
	
	struct int16v4 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				int16	x, y, z, w;
			};
			int16		arr[4];
		};
		
		// Component indexing operator
		int16& operator[] (int i);
		
		// Component indexing operator
		int16 const& operator[] (int i) const;
		
		
		// uninitialized constructor
		int16v4 ();
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		int16v4 (int16 all);
		
		// supply all components
		int16v4 (int16 x, int16 y, int16 z, int16 w);
		
		// extend vector
		int16v4 (int16v2 xy, int16 z, int16 w);
		
		// extend vector
		int16v4 (int16v3 xyz, int16 w);
		
		
		//// Truncating cast operators
		
		// truncating cast operator
		explicit operator int16v2 () const;
		
		// truncating cast operator
		explicit operator int16v3 () const;
		
		
		//// Type cast operators
		
		// type cast operator
		explicit operator bool4 () const;
		
		// type cast operator
		explicit operator float4 () const;
		
		// type cast operator
		explicit operator double4 () const;
		
		// type cast operator
		explicit operator int8v4 () const;
		
		// type cast operator
		explicit operator int4 () const;
		
		// type cast operator
		explicit operator int64v4 () const;
		
		// type cast operator
		explicit operator uint8v4 () const;
		
		// type cast operator
		explicit operator uint16v4 () const;
		
		// type cast operator
		explicit operator uint4 () const;
		
		// type cast operator
		explicit operator uint64v4 () const;
		
		
		// componentwise arithmetic operator
		int16v4 operator+= (int16v4 r);
		
		// componentwise arithmetic operator
		int16v4 operator-= (int16v4 r);
		
		// componentwise arithmetic operator
		int16v4 operator*= (int16v4 r);
		
		// componentwise arithmetic operator
		int16v4 operator/= (int16v4 r);
		
	};
	
	//// arthmethic ops
	
	int16v4 operator+ (int16v4 v);
	
	int16v4 operator- (int16v4 v);
	
	int16v4 operator+ (int16v4 l, int16v4 r);
	
	int16v4 operator- (int16v4 l, int16v4 r);
	
	int16v4 operator* (int16v4 l, int16v4 r);
	
	int16v4 operator/ (int16v4 l, int16v4 r);
	
	
	//// bitwise ops
	
	int16v4 operator~ (int16v4 v);
	
	int16v4 operator& (int16v4 l, int16v4 r);
	
	int16v4 operator| (int16v4 l, int16v4 r);
	
	int16v4 operator^ (int16v4 l, int16v4 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	bool4 operator< (int16v4 l, int16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator<= (int16v4 l, int16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator> (int16v4 l, int16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator>= (int16v4 l, int16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator== (int16v4 l, int16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator!= (int16v4 l, int16v4 r);
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (int16v4 l, int16v4 r);
	
	// componentwise ternary (c ? l : r)
	int16v4 select (bool4 c, int16v4 l, int16v4 r);
	
	
	//// misc ops
	// componentwise absolute
	int16v4 abs (int16v4 v);
	
	// componentwise minimum
	int16v4 min (int16v4 l, int16v4 r);
	
	// componentwise maximum
	int16v4 max (int16v4 l, int16v4 r);
	
	// componentwise clamp into range [a,b]
	int16v4 clamp (int16v4 x, int16v4 a, int16v4 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	int16v4 clamp (int16v4 x);
	
	// get minimum component of vector, optionally get component index via min_index
	int16 min_component (int16v4 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	int16 max_component (int16v4 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	int16v4 wrap (int16v4 v, int16v4 range);
	
	// componentwise wrap
	int16v4 wrap (int16v4 v, int16v4 a, int16v4 b);
	
	
	
	//// Vector math
	
	// magnitude of vector
	float length (int16v4 v);
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	int16 length_sqr (int16v4 v);
	
	// distance between points, equivalent to length(a - b)
	float distance (int16v4 a, int16v4 b);
	
	// normalize vector so that it has length() = 1, undefined for zero vector
	float4 normalize (int16v4 v);
	
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	float4 normalizesafe (int16v4 v);
	
	// dot product
	int16 dot (int16v4 l, int16v4 r);
	
}

