// file was generated by kissmath.py at <TODO: add github link>
#include "int16v2.hpp"

#include "int16v3.hpp"
#include "int64v2.hpp"
#include "uint2.hpp"
#include "bool2.hpp"
#include "int16v4.hpp"
#include "float2.hpp"
#include "uint16v2.hpp"
#include "double2.hpp"
#include "int2.hpp"
#include "int8v2.hpp"
#include "uint64v2.hpp"
#include "uint8v2.hpp"

namespace kissmath {
	//// forward declarations
	// typedef these because the _t suffix is kinda unwieldy when using these types often
	
	typedef int16_t int16;
	typedef int64_t int64;
	typedef unsigned int uint;
	typedef int16_t int16;
	typedef uint16_t uint16;
	typedef int8_t int8;
	typedef uint64_t uint64;
	typedef uint8_t uint8;
	
	// Component indexing operator
	int16& int16v2::operator[] (int i) {
		return arr[i];
	}
	
	// Component indexing operator
	int16 const& int16v2::operator[] (int i) const {
		return arr[i];
	}
	
	
	// uninitialized constructor
	int16v2::int16v2 () {
		
	}
	
	// sets all components to one value
	// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
	// and short initialization like float3 a = 0; works
	int16v2::int16v2 (int16 all): x{all}, y{all} {
		
	}
	
	// supply all components
	int16v2::int16v2 (int16 x, int16 y): x{x}, y{y} {
		
	}
	
	// truncate vector
	int16v2::int16v2 (int16v3 v): x{v.x}, y{v.y} {
		
	}
	
	// truncate vector
	int16v2::int16v2 (int16v4 v): x{v.x}, y{v.y} {
		
	}
	
	//// Truncating cast operators
	
	
	//// Type cast operators
	
	
	// type cast operator
	int16v2::operator bool2 () const {
		return bool2((bool)x, (bool)y);
	}
	
	// type cast operator
	int16v2::operator float2 () const {
		return float2((float)x, (float)y);
	}
	
	// type cast operator
	int16v2::operator double2 () const {
		return double2((double)x, (double)y);
	}
	
	// type cast operator
	int16v2::operator int8v2 () const {
		return int8v2((int8)x, (int8)y);
	}
	
	// type cast operator
	int16v2::operator int2 () const {
		return int2((int)x, (int)y);
	}
	
	// type cast operator
	int16v2::operator int64v2 () const {
		return int64v2((int64)x, (int64)y);
	}
	
	// type cast operator
	int16v2::operator uint8v2 () const {
		return uint8v2((uint8)x, (uint8)y);
	}
	
	// type cast operator
	int16v2::operator uint16v2 () const {
		return uint16v2((uint16)x, (uint16)y);
	}
	
	// type cast operator
	int16v2::operator uint2 () const {
		return uint2((uint)x, (uint)y);
	}
	
	// type cast operator
	int16v2::operator uint64v2 () const {
		return uint64v2((uint64)x, (uint64)y);
	}
	
	
	// componentwise arithmetic operator
	int16v2 int16v2::operator+= (int16v2 r) {
		x += r.x;
		y += r.y;
		return *this;
	}
	
	// componentwise arithmetic operator
	int16v2 int16v2::operator-= (int16v2 r) {
		x -= r.x;
		y -= r.y;
		return *this;
	}
	
	// componentwise arithmetic operator
	int16v2 int16v2::operator*= (int16v2 r) {
		x *= r.x;
		y *= r.y;
		return *this;
	}
	
	// componentwise arithmetic operator
	int16v2 int16v2::operator/= (int16v2 r) {
		x /= r.x;
		y /= r.y;
		return *this;
	}
	
	//// arthmethic ops
	
	
	int16v2 operator+ (int16v2 v) {
		return int16v2(+v.x, +v.y);
	}
	
	int16v2 operator- (int16v2 v) {
		return int16v2(-v.x, -v.y);
	}
	
	int16v2 operator+ (int16v2 l, int16v2 r) {
		return int16v2(l.x + r.x, l.y + r.y);
	}
	
	int16v2 operator- (int16v2 l, int16v2 r) {
		return int16v2(l.x - r.x, l.y - r.y);
	}
	
	int16v2 operator* (int16v2 l, int16v2 r) {
		return int16v2(l.x * r.x, l.y * r.y);
	}
	
	int16v2 operator/ (int16v2 l, int16v2 r) {
		return int16v2(l.x / r.x, l.y / r.y);
	}
	
	//// bitwise ops
	
	
	int16v2 operator~ (int16v2 v) {
		return int16v2(~v.x, ~v.y);
	}
	
	int16v2 operator& (int16v2 l, int16v2 r) {
		return int16v2(l.x & r.x, l.y & r.y);
	}
	
	int16v2 operator| (int16v2 l, int16v2 r) {
		return int16v2(l.x | r.x, l.y | r.y);
	}
	
	int16v2 operator^ (int16v2 l, int16v2 r) {
		return int16v2(l.x ^ r.x, l.y ^ r.y);
	}
	
	//// comparison ops
	
	
	// componentwise comparison returns a bool vector
	bool2 operator< (int16v2 l, int16v2 r) {
		return bool2(l.x < r.x, l.y < r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator<= (int16v2 l, int16v2 r) {
		return bool2(l.x <= r.x, l.y <= r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator> (int16v2 l, int16v2 r) {
		return bool2(l.x > r.x, l.y > r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator>= (int16v2 l, int16v2 r) {
		return bool2(l.x >= r.x, l.y >= r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator== (int16v2 l, int16v2 r) {
		return bool2(l.x == r.x, l.y == r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator!= (int16v2 l, int16v2 r) {
		return bool2(l.x != r.x, l.y != r.y);
	}
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (int16v2 l, int16v2 r) {
		return all(l == r);
	}
	
	// componentwise ternary (c ? l : r)
	int16v2 select (bool2 c, int16v2 l, int16v2 r) {
		return int16v2(c.x ? l.x : r.x, c.y ? l.y : r.y);
	}
	
	//// misc ops
	
	// componentwise absolute
	int16v2 abs (int16v2 v) {
		return int16v2(abs(v.x), abs(v.y));
	}
	
	// componentwise minimum
	int16v2 min (int16v2 l, int16v2 r) {
		return int16v2(min(l.x,r.x), min(l.y,r.y));
	}
	
	// componentwise maximum
	int16v2 max (int16v2 l, int16v2 r) {
		return int16v2(max(l.x,r.x), max(l.y,r.y));
	}
	
	// componentwise clamp into range [a,b]
	int16v2 clamp (int16v2 x, int16v2 a, int16v2 b) {
		return min(max(x,a), b);
	}
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	int16v2 clamp (int16v2 x) {
		return min(max(x, int16(0)), int16(1));
	}
	
	// get minimum component of vector, optionally get component index via min_index
	int16 min_component (int16v2 v, int* min_index) {
		int index = 0;
		int16 min_val = v.x;	
		for (int i=1; i<2; ++i) {
			if (v.arr[i] <= min_val) {
				index = i;
				min_val = v.arr[i];
			}
		}
		if (min_index) *min_index = index;
		return min_val;
	}
	
	// get maximum component of vector, optionally get component index via max_index
	int16 max_component (int16v2 v, int* max_index) {
		int index = 0;
		int16 max_val = v.x;	
		for (int i=1; i<2; ++i) {
			if (v.arr[i] >= max_val) {
				index = i;
				max_val = v.arr[i];
			}
		}
		if (max_index) *max_index = index;
		return max_val;
	}
	
	
	// componentwise wrap
	int16v2 wrap (int16v2 v, int16v2 range) {
		return int16v2(wrap(v.x,range.x), wrap(v.y,range.y));
	}
	
	// componentwise wrap
	int16v2 wrap (int16v2 v, int16v2 a, int16v2 b) {
		return int16v2(wrap(v.x,a.x,b.x), wrap(v.y,a.y,b.y));
	}
	
	
	//// Vector math
	
	
	// magnitude of vector
	float length (int16v2 v) {
		return sqrt((float)(v.x * v.x + v.y * v.y));
	}
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	int16 length_sqr (int16v2 v) {
		return v.x * v.x + v.y * v.y;
	}
	
	// distance between points, equivalent to length(a - b)
	float distance (int16v2 a, int16v2 b) {
		return length(a - b);
	}
	
	// normalize vector so that it has length() = 1, undefined for zero vector
	float2 normalize (int16v2 v) {
		return float2(v) / length(v);
	}
	
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	float2 normalizesafe (int16v2 v) {
		float len = length(v);
		if (len == float(0)) {
			return float(0);
		}
		return float2(v) / float2(len);
	}
	
	// dot product
	int16 dot (int16v2 l, int16v2 r) {
		return l.x * r.x + l.y * r.y;
	}
	
	// 2d cross product hack for convenient 2d stuff
	// same as cross({T.name[:-2]}3(l, 0), {T.name[:-2]}3(r, 0)).z,
	// ie. the cross product of the 2d vectors on the z=0 plane in 3d space and then return the z coord of that (signed mag of cross product)
	int16 cross (int16v2 l, int16v2 r) {
		return l.x * r.y - l.y * r.x;
	}
	
	// rotate 2d vector counterclockwise 90 deg, ie. int16v2(-y, x) which is fast
	int16v2 rotate90 (int16v2 v) {
		return int16v2(-v.y, v.x);
	}
}

