// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include <cmath>
#include <cstdint>

namespace kissmath {
	typedef int16_t int16; // typedef this because the _t suffix is kinda unwieldy when using these types often
	
	// Use std math functions for these
	using std::abs;
	using std::floor;
	using std::ceil;
	using std::pow;
	using std::round;
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	int16 wrap (int16 x, int16 range);
	
	// wrap x into [a,b) range
	int16 wrap (int16 x, int16 a, int16 b);
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	int16 clamp (int16 x, int16 a, int16 b);
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	int16 clamp (int16 x);
	
	// returns the greater value of a and b
	int16 min (int16 l, int16 r);
	
	// returns the smaller value of a and b
	int16 max (int16 l, int16 r);
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	int16 select (bool c, int16 l, int16 r);
	
	
	// length(scalar) = abs(scalar)
	// for conformity with vectors
	int16 length (int16 x);
	
	// length_sqr(scalar) = abs(scalar)^2
	// for conformity with vectors (for vectors this func is preferred over length to avoid the sqrt)
	int16 length_sqr (int16 x);
	
	// scalar normalize for conformity with vectors
	// normalize(-6.2f) = -1f, normalize(7) = 1, normalize(0) = <div 0>
	// can be useful in some cases
	int16 normalize (int16 x);
	
	// normalize(x) for length(x) != 0 else 0
	int16 normalizesafe (int16 x);
	
	
}

