// file was generated by kissmath.py at <TODO: add github link>
#include "int8.hpp"

namespace kissmath {
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	int8 wrap (int8 x, int8 range) {
		int8 modded = x % range;
		if (range > 0) {
			if (modded < 0) modded += range;
		} else {
			if (modded > 0) modded += range;
		}
		return modded;
	}
	
	// wrap x into [a,b) range
	int8 wrap (int8 x, int8 a, int8 b) {
		x -= a;
		int8 range = b -a;
		
		int8 modulo = wrap(x, range);
		
		return modulo + a;
	}
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	int8 clamp (int8 x, int8 a, int8 b) {
		return min(max(x, a), b);
	}
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	int8 clamp (int8 x) {
		return min(max(x, int8(0)), int8(1));
	}
	
	// returns the greater value of a and b
	int8 min (int8 l, int8 r) {
		return l <= r ? l : r;
	}
	
	// returns the smaller value of a and b
	int8 max (int8 l, int8 r) {
		return l >= r ? l : r;
	}
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	int8 select (bool c, int8 l, int8 r) {
		return c ? l : r;
	}
	
	
	// length(scalar) = abs(scalar)
	// for conformity with vectors
	int8 length (int8 x) {
		return std::abs(x);
	}
	
	// length_sqr(scalar) = abs(scalar)^2
	// for conformity with vectors (for vectors this func is preferred over length to avoid the sqrt)
	int8 length_sqr (int8 x) {
		x = std::abs(x);
		return x*x;
	}
	
	// scalar normalize for conformity with vectors
	// normalize(-6.2f) = -1f, normalize(7) = 1, normalize(0) = <div 0>
	// can be useful in some cases
	int8 normalize (int8 x) {
		return x / length(x);
	}
	
	// normalize(x) for length(x) != 0 else 0
	int8 normalizesafe (int8 x) {
		int8 len = length(x);
		if (len == int8(0)) {
			return int8(0);
		}
		return x /= len;
	}
	
}

