// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include <cmath>
#include <cstdint>

namespace kissmath {
	typedef int8_t int8; // typedef this because the _t suffix is kinda unwieldy when using these types often
	
	// Use std math functions for these
	using std::abs;
	using std::floor;
	using std::ceil;
	using std::pow;
	using std::round;
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	int8 wrap (int8 x, int8 range);
	
	// wrap x into [a,b) range
	int8 wrap (int8 x, int8 a, int8 b);
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	int8 clamp (int8 x, int8 a, int8 b);
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	int8 clamp (int8 x);
	
	// returns the greater value of a and b
	int8 min (int8 l, int8 r);
	
	// returns the smaller value of a and b
	int8 max (int8 l, int8 r);
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	int8 select (bool c, int8 l, int8 r);
	
	
	// length(scalar) = abs(scalar)
	// for conformity with vectors
	int8 length (int8 x);
	
	// length_sqr(scalar) = abs(scalar)^2
	// for conformity with vectors (for vectors this func is preferred over length to avoid the sqrt)
	int8 length_sqr (int8 x);
	
	// scalar normalize for conformity with vectors
	// normalize(-6.2f) = -1f, normalize(7) = 1, normalize(0) = <div 0>
	// can be useful in some cases
	int8 normalize (int8 x);
	
	// normalize(x) for length(x) != 0 else 0
	int8 normalizesafe (int8 x);
	
	
}

