// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "float2.hpp"
#include "float2x2.hpp"
#include "float2x3.hpp"

#include "double2.hpp"
#include "double2x2.hpp"
#include "double2x3.hpp"

namespace kissmath {
	
	float2x2 rotate2 (float ang);
	
	float2x2 scale (float2 v);
	
	float2x3 translate (float2 v);
	
	
	double2x2 rotate2 (double ang);
	
	double2x2 scale (double2 v);
	
	double2x3 translate (double2 v);
	
	
}

