// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "uint64.hpp"

namespace kissmath {
	//// forward declarations
	
	struct uint64v3;
	struct uint64v4;
	struct int64v2;
	struct uint2;
	struct bool2;
	struct float2;
	struct uint16v2;
	struct int16v2;
	struct double2;
	struct int2;
	struct int8v2;
	struct uint8v2;
	
	struct uint64v2 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				uint64	x, y;
			};
			uint64		arr[2];
		};
		
		// Component indexing operator
		uint64& operator[] (int i);
		
		// Component indexing operator
		uint64 const& operator[] (int i) const;
		
		
		// uninitialized constructor
		uint64v2 ();
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		uint64v2 (uint64 all);
		
		// supply all components
		uint64v2 (uint64 x, uint64 y);
		
		// truncate vector
		uint64v2 (uint64v3 v);
		
		// truncate vector
		uint64v2 (uint64v4 v);
		
		
		//// Truncating cast operators
		
		
		//// Type cast operators
		
		// type cast operator
		explicit operator bool2 () const;
		
		// type cast operator
		explicit operator float2 () const;
		
		// type cast operator
		explicit operator double2 () const;
		
		// type cast operator
		explicit operator int8v2 () const;
		
		// type cast operator
		explicit operator int16v2 () const;
		
		// type cast operator
		explicit operator int2 () const;
		
		// type cast operator
		explicit operator int64v2 () const;
		
		// type cast operator
		explicit operator uint8v2 () const;
		
		// type cast operator
		explicit operator uint16v2 () const;
		
		// type cast operator
		explicit operator uint2 () const;
		
		
		// componentwise arithmetic operator
		uint64v2 operator+= (uint64v2 r);
		
		// componentwise arithmetic operator
		uint64v2 operator-= (uint64v2 r);
		
		// componentwise arithmetic operator
		uint64v2 operator*= (uint64v2 r);
		
		// componentwise arithmetic operator
		uint64v2 operator/= (uint64v2 r);
		
	};
	
	//// arthmethic ops
	
	uint64v2 operator+ (uint64v2 v);
	
	uint64v2 operator+ (uint64v2 l, uint64v2 r);
	
	uint64v2 operator- (uint64v2 l, uint64v2 r);
	
	uint64v2 operator* (uint64v2 l, uint64v2 r);
	
	uint64v2 operator/ (uint64v2 l, uint64v2 r);
	
	
	//// bitwise ops
	
	uint64v2 operator~ (uint64v2 v);
	
	uint64v2 operator& (uint64v2 l, uint64v2 r);
	
	uint64v2 operator| (uint64v2 l, uint64v2 r);
	
	uint64v2 operator^ (uint64v2 l, uint64v2 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	bool2 operator< (uint64v2 l, uint64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator<= (uint64v2 l, uint64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator> (uint64v2 l, uint64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator>= (uint64v2 l, uint64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator== (uint64v2 l, uint64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator!= (uint64v2 l, uint64v2 r);
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (uint64v2 l, uint64v2 r);
	
	// componentwise ternary (c ? l : r)
	uint64v2 select (bool2 c, uint64v2 l, uint64v2 r);
	
	
	//// misc ops
	// componentwise minimum
	uint64v2 min (uint64v2 l, uint64v2 r);
	
	// componentwise maximum
	uint64v2 max (uint64v2 l, uint64v2 r);
	
	// componentwise clamp into range [a,b]
	uint64v2 clamp (uint64v2 x, uint64v2 a, uint64v2 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	uint64v2 clamp (uint64v2 x);
	
	// get minimum component of vector, optionally get component index via min_index
	uint64 min_component (uint64v2 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	uint64 max_component (uint64v2 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	uint64v2 wrap (uint64v2 v, uint64v2 range);
	
	// componentwise wrap
	uint64v2 wrap (uint64v2 v, uint64v2 a, uint64v2 b);
	
	
	
	//// Vector math
	
}

