// file was generated by kissmath.py at <TODO: add github link>
#include "uint16.hpp"

namespace kissmath {
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	uint16 wrap (uint16 x, uint16 range) {
		uint16 modded = x % range;
		if (range > 0) {
			if (modded < 0) modded += range;
		} else {
			if (modded > 0) modded += range;
		}
		return modded;
	}
	
	// wrap x into [a,b) range
	uint16 wrap (uint16 x, uint16 a, uint16 b) {
		x -= a;
		uint16 range = b -a;
		
		uint16 modulo = wrap(x, range);
		
		return modulo + a;
	}
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	uint16 clamp (uint16 x, uint16 a, uint16 b) {
		return min(max(x, a), b);
	}
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	uint16 clamp (uint16 x) {
		return min(max(x, uint16(0)), uint16(1));
	}
	
	// returns the greater value of a and b
	uint16 min (uint16 l, uint16 r) {
		return l <= r ? l : r;
	}
	
	// returns the smaller value of a and b
	uint16 max (uint16 l, uint16 r) {
		return l >= r ? l : r;
	}
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	uint16 select (bool c, uint16 l, uint16 r) {
		return c ? l : r;
	}
	
}

