// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include <cmath>
#include <cstdint>

namespace kissmath {
	typedef uint16_t uint16; // typedef this because the _t suffix is kinda unwieldy when using these types often
	
	// Use std math functions for these
	using std::abs;
	using std::floor;
	using std::ceil;
	using std::pow;
	using std::round;
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	uint16 wrap (uint16 x, uint16 range);
	
	// wrap x into [a,b) range
	uint16 wrap (uint16 x, uint16 a, uint16 b);
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	uint16 clamp (uint16 x, uint16 a, uint16 b);
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	uint16 clamp (uint16 x);
	
	// returns the greater value of a and b
	uint16 min (uint16 l, uint16 r);
	
	// returns the smaller value of a and b
	uint16 max (uint16 l, uint16 r);
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	uint16 select (bool c, uint16 l, uint16 r);
	
	
}

