// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "uint.hpp"

namespace kissmath {
	//// forward declarations
	
	struct double4;
	struct uint16v4;
	struct uint3;
	struct int64v4;
	struct uint64v4;
	struct int8v4;
	struct int16v4;
	struct bool4;
	struct uint2;
	struct int4;
	struct float4;
	struct uint8v4;
	
	struct uint4 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				uint	x, y, z, w;
			};
			uint		arr[4];
		};
		
		// Component indexing operator
		uint& operator[] (int i);
		
		// Component indexing operator
		uint const& operator[] (int i) const;
		
		
		// uninitialized constructor
		uint4 ();
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		uint4 (uint all);
		
		// supply all components
		uint4 (uint x, uint y, uint z, uint w);
		
		// extend vector
		uint4 (uint2 xy, uint z, uint w);
		
		// extend vector
		uint4 (uint3 xyz, uint w);
		
		
		//// Truncating cast operators
		
		// truncating cast operator
		explicit operator uint2 () const;
		
		// truncating cast operator
		explicit operator uint3 () const;
		
		
		//// Type cast operators
		
		// type cast operator
		explicit operator bool4 () const;
		
		// type cast operator
		explicit operator float4 () const;
		
		// type cast operator
		explicit operator double4 () const;
		
		// type cast operator
		explicit operator int8v4 () const;
		
		// type cast operator
		explicit operator int16v4 () const;
		
		// type cast operator
		explicit operator int4 () const;
		
		// type cast operator
		explicit operator int64v4 () const;
		
		// type cast operator
		explicit operator uint8v4 () const;
		
		// type cast operator
		explicit operator uint16v4 () const;
		
		// type cast operator
		explicit operator uint64v4 () const;
		
		
		// componentwise arithmetic operator
		uint4 operator+= (uint4 r);
		
		// componentwise arithmetic operator
		uint4 operator-= (uint4 r);
		
		// componentwise arithmetic operator
		uint4 operator*= (uint4 r);
		
		// componentwise arithmetic operator
		uint4 operator/= (uint4 r);
		
	};
	
	//// arthmethic ops
	
	uint4 operator+ (uint4 v);
	
	uint4 operator+ (uint4 l, uint4 r);
	
	uint4 operator- (uint4 l, uint4 r);
	
	uint4 operator* (uint4 l, uint4 r);
	
	uint4 operator/ (uint4 l, uint4 r);
	
	
	//// bitwise ops
	
	uint4 operator~ (uint4 v);
	
	uint4 operator& (uint4 l, uint4 r);
	
	uint4 operator| (uint4 l, uint4 r);
	
	uint4 operator^ (uint4 l, uint4 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	bool4 operator< (uint4 l, uint4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator<= (uint4 l, uint4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator> (uint4 l, uint4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator>= (uint4 l, uint4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator== (uint4 l, uint4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator!= (uint4 l, uint4 r);
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (uint4 l, uint4 r);
	
	// componentwise ternary (c ? l : r)
	uint4 select (bool4 c, uint4 l, uint4 r);
	
	
	//// misc ops
	// componentwise minimum
	uint4 min (uint4 l, uint4 r);
	
	// componentwise maximum
	uint4 max (uint4 l, uint4 r);
	
	// componentwise clamp into range [a,b]
	uint4 clamp (uint4 x, uint4 a, uint4 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	uint4 clamp (uint4 x);
	
	// get minimum component of vector, optionally get component index via min_index
	uint min_component (uint4 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	uint max_component (uint4 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	uint4 wrap (uint4 v, uint4 range);
	
	// componentwise wrap
	uint4 wrap (uint4 v, uint4 a, uint4 b);
	
	
	
	//// Vector math
	
}

