// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "uint.hpp"

namespace kissmath {
	//// forward declarations
	
	struct uint4;
	struct int64v2;
	struct bool2;
	struct float2;
	struct uint3;
	struct uint16v2;
	struct int16v2;
	struct double2;
	struct int2;
	struct int8v2;
	struct uint64v2;
	struct uint8v2;
	
	struct uint2 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				uint	x, y;
			};
			uint		arr[2];
		};
		
		// Component indexing operator
		uint& operator[] (int i);
		
		// Component indexing operator
		uint const& operator[] (int i) const;
		
		
		// uninitialized constructor
		uint2 ();
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		uint2 (uint all);
		
		// supply all components
		uint2 (uint x, uint y);
		
		// truncate vector
		uint2 (uint3 v);
		
		// truncate vector
		uint2 (uint4 v);
		
		
		//// Truncating cast operators
		
		
		//// Type cast operators
		
		// type cast operator
		explicit operator bool2 () const;
		
		// type cast operator
		explicit operator float2 () const;
		
		// type cast operator
		explicit operator double2 () const;
		
		// type cast operator
		explicit operator int8v2 () const;
		
		// type cast operator
		explicit operator int16v2 () const;
		
		// type cast operator
		explicit operator int2 () const;
		
		// type cast operator
		explicit operator int64v2 () const;
		
		// type cast operator
		explicit operator uint8v2 () const;
		
		// type cast operator
		explicit operator uint16v2 () const;
		
		// type cast operator
		explicit operator uint64v2 () const;
		
		
		// componentwise arithmetic operator
		uint2 operator+= (uint2 r);
		
		// componentwise arithmetic operator
		uint2 operator-= (uint2 r);
		
		// componentwise arithmetic operator
		uint2 operator*= (uint2 r);
		
		// componentwise arithmetic operator
		uint2 operator/= (uint2 r);
		
	};
	
	//// arthmethic ops
	
	uint2 operator+ (uint2 v);
	
	uint2 operator+ (uint2 l, uint2 r);
	
	uint2 operator- (uint2 l, uint2 r);
	
	uint2 operator* (uint2 l, uint2 r);
	
	uint2 operator/ (uint2 l, uint2 r);
	
	
	//// bitwise ops
	
	uint2 operator~ (uint2 v);
	
	uint2 operator& (uint2 l, uint2 r);
	
	uint2 operator| (uint2 l, uint2 r);
	
	uint2 operator^ (uint2 l, uint2 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	bool2 operator< (uint2 l, uint2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator<= (uint2 l, uint2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator> (uint2 l, uint2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator>= (uint2 l, uint2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator== (uint2 l, uint2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator!= (uint2 l, uint2 r);
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (uint2 l, uint2 r);
	
	// componentwise ternary (c ? l : r)
	uint2 select (bool2 c, uint2 l, uint2 r);
	
	
	//// misc ops
	// componentwise minimum
	uint2 min (uint2 l, uint2 r);
	
	// componentwise maximum
	uint2 max (uint2 l, uint2 r);
	
	// componentwise clamp into range [a,b]
	uint2 clamp (uint2 x, uint2 a, uint2 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	uint2 clamp (uint2 x);
	
	// get minimum component of vector, optionally get component index via min_index
	uint min_component (uint2 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	uint max_component (uint2 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	uint2 wrap (uint2 v, uint2 range);
	
	// componentwise wrap
	uint2 wrap (uint2 v, uint2 a, uint2 b);
	
	
	
	//// Vector math
	
}

