// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "uint64.hpp"

namespace kissmath {
	//// forward declarations
	
	struct uint3;
	struct int8v3;
	struct int16v3;
	struct double3;
	struct uint64v2;
	struct uint16v3;
	struct uint64v4;
	struct bool3;
	struct int64v3;
	struct float3;
	struct int3;
	struct uint8v3;
	
	struct uint64v3 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				uint64	x, y, z;
			};
			uint64		arr[3];
		};
		
		// Component indexing operator
		uint64& operator[] (int i);
		
		// Component indexing operator
		uint64 const& operator[] (int i) const;
		
		
		// uninitialized constructor
		uint64v3 ();
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		uint64v3 (uint64 all);
		
		// supply all components
		uint64v3 (uint64 x, uint64 y, uint64 z);
		
		// extend vector
		uint64v3 (uint64v2 xy, uint64 z);
		
		// truncate vector
		uint64v3 (uint64v4 v);
		
		
		//// Truncating cast operators
		
		// truncating cast operator
		explicit operator uint64v2 () const;
		
		
		//// Type cast operators
		
		// type cast operator
		explicit operator bool3 () const;
		
		// type cast operator
		explicit operator float3 () const;
		
		// type cast operator
		explicit operator double3 () const;
		
		// type cast operator
		explicit operator int8v3 () const;
		
		// type cast operator
		explicit operator int16v3 () const;
		
		// type cast operator
		explicit operator int3 () const;
		
		// type cast operator
		explicit operator int64v3 () const;
		
		// type cast operator
		explicit operator uint8v3 () const;
		
		// type cast operator
		explicit operator uint16v3 () const;
		
		// type cast operator
		explicit operator uint3 () const;
		
		
		// componentwise arithmetic operator
		uint64v3 operator+= (uint64v3 r);
		
		// componentwise arithmetic operator
		uint64v3 operator-= (uint64v3 r);
		
		// componentwise arithmetic operator
		uint64v3 operator*= (uint64v3 r);
		
		// componentwise arithmetic operator
		uint64v3 operator/= (uint64v3 r);
		
	};
	
	//// arthmethic ops
	
	uint64v3 operator+ (uint64v3 v);
	
	uint64v3 operator+ (uint64v3 l, uint64v3 r);
	
	uint64v3 operator- (uint64v3 l, uint64v3 r);
	
	uint64v3 operator* (uint64v3 l, uint64v3 r);
	
	uint64v3 operator/ (uint64v3 l, uint64v3 r);
	
	
	//// bitwise ops
	
	uint64v3 operator~ (uint64v3 v);
	
	uint64v3 operator& (uint64v3 l, uint64v3 r);
	
	uint64v3 operator| (uint64v3 l, uint64v3 r);
	
	uint64v3 operator^ (uint64v3 l, uint64v3 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	bool3 operator< (uint64v3 l, uint64v3 r);
	
	// componentwise comparison returns a bool vector
	bool3 operator<= (uint64v3 l, uint64v3 r);
	
	// componentwise comparison returns a bool vector
	bool3 operator> (uint64v3 l, uint64v3 r);
	
	// componentwise comparison returns a bool vector
	bool3 operator>= (uint64v3 l, uint64v3 r);
	
	// componentwise comparison returns a bool vector
	bool3 operator== (uint64v3 l, uint64v3 r);
	
	// componentwise comparison returns a bool vector
	bool3 operator!= (uint64v3 l, uint64v3 r);
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (uint64v3 l, uint64v3 r);
	
	// componentwise ternary (c ? l : r)
	uint64v3 select (bool3 c, uint64v3 l, uint64v3 r);
	
	
	//// misc ops
	// componentwise minimum
	uint64v3 min (uint64v3 l, uint64v3 r);
	
	// componentwise maximum
	uint64v3 max (uint64v3 l, uint64v3 r);
	
	// componentwise clamp into range [a,b]
	uint64v3 clamp (uint64v3 x, uint64v3 a, uint64v3 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	uint64v3 clamp (uint64v3 x);
	
	// get minimum component of vector, optionally get component index via min_index
	uint64 min_component (uint64v3 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	uint64 max_component (uint64v3 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	uint64v3 wrap (uint64v3 v, uint64v3 range);
	
	// componentwise wrap
	uint64v3 wrap (uint64v3 v, uint64v3 a, uint64v3 b);
	
	
	
	//// Vector math
	
}

