// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "uint16.hpp"

namespace kissmath {
	//// forward declarations
	
	struct uint8v4;
	struct uint4;
	struct int64v4;
	struct uint16v2;
	struct int8v4;
	struct float4;
	struct bool4;
	struct uint16v3;
	struct uint64v4;
	struct int16v4;
	struct double4;
	struct int4;
	
	struct uint16v4 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				uint16	x, y, z, w;
			};
			uint16		arr[4];
		};
		
		// Component indexing operator
		uint16& operator[] (int i);
		
		// Component indexing operator
		uint16 const& operator[] (int i) const;
		
		
		// uninitialized constructor
		uint16v4 ();
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		uint16v4 (uint16 all);
		
		// supply all components
		uint16v4 (uint16 x, uint16 y, uint16 z, uint16 w);
		
		// extend vector
		uint16v4 (uint16v2 xy, uint16 z, uint16 w);
		
		// extend vector
		uint16v4 (uint16v3 xyz, uint16 w);
		
		
		//// Truncating cast operators
		
		// truncating cast operator
		explicit operator uint16v2 () const;
		
		// truncating cast operator
		explicit operator uint16v3 () const;
		
		
		//// Type cast operators
		
		// type cast operator
		explicit operator bool4 () const;
		
		// type cast operator
		explicit operator float4 () const;
		
		// type cast operator
		explicit operator double4 () const;
		
		// type cast operator
		explicit operator int8v4 () const;
		
		// type cast operator
		explicit operator int16v4 () const;
		
		// type cast operator
		explicit operator int4 () const;
		
		// type cast operator
		explicit operator int64v4 () const;
		
		// type cast operator
		explicit operator uint8v4 () const;
		
		// type cast operator
		explicit operator uint4 () const;
		
		// type cast operator
		explicit operator uint64v4 () const;
		
		
		// componentwise arithmetic operator
		uint16v4 operator+= (uint16v4 r);
		
		// componentwise arithmetic operator
		uint16v4 operator-= (uint16v4 r);
		
		// componentwise arithmetic operator
		uint16v4 operator*= (uint16v4 r);
		
		// componentwise arithmetic operator
		uint16v4 operator/= (uint16v4 r);
		
	};
	
	//// arthmethic ops
	
	uint16v4 operator+ (uint16v4 v);
	
	uint16v4 operator+ (uint16v4 l, uint16v4 r);
	
	uint16v4 operator- (uint16v4 l, uint16v4 r);
	
	uint16v4 operator* (uint16v4 l, uint16v4 r);
	
	uint16v4 operator/ (uint16v4 l, uint16v4 r);
	
	
	//// bitwise ops
	
	uint16v4 operator~ (uint16v4 v);
	
	uint16v4 operator& (uint16v4 l, uint16v4 r);
	
	uint16v4 operator| (uint16v4 l, uint16v4 r);
	
	uint16v4 operator^ (uint16v4 l, uint16v4 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	bool4 operator< (uint16v4 l, uint16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator<= (uint16v4 l, uint16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator> (uint16v4 l, uint16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator>= (uint16v4 l, uint16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator== (uint16v4 l, uint16v4 r);
	
	// componentwise comparison returns a bool vector
	bool4 operator!= (uint16v4 l, uint16v4 r);
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (uint16v4 l, uint16v4 r);
	
	// componentwise ternary (c ? l : r)
	uint16v4 select (bool4 c, uint16v4 l, uint16v4 r);
	
	
	//// misc ops
	// componentwise minimum
	uint16v4 min (uint16v4 l, uint16v4 r);
	
	// componentwise maximum
	uint16v4 max (uint16v4 l, uint16v4 r);
	
	// componentwise clamp into range [a,b]
	uint16v4 clamp (uint16v4 x, uint16v4 a, uint16v4 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	uint16v4 clamp (uint16v4 x);
	
	// get minimum component of vector, optionally get component index via min_index
	uint16 min_component (uint16v4 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	uint16 max_component (uint16v4 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	uint16v4 wrap (uint16v4 v, uint16v4 range);
	
	// componentwise wrap
	uint16v4 wrap (uint16v4 v, uint16v4 a, uint16v4 b);
	
	
	
	//// Vector math
	
}

